### ISSUE TITLE
Unable to load add-on

### ISSUE THREAD

**Issue by taihendesu** [Sabicool/Malleus-Anki-Addon#1]
<img width="502" alt="Screenshot 2024-12-07 at 1 15 19 PM" src="https://github.com/user-attachments/assets/f384ecbb-d43d-45f4-92f2-3fbea269220a">

Have tried reinstalling anki app and add-on to no effect.

Debug info: 

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-11.7.7-x86_64-i386-64bit

When loading Malleus Anki Helper Addon:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/justin.ng/Library/Application Support/Anki2/addons21/620451841/__init__.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by Sabicool** [comment]
Thank you for creating your issue. May I also know what other add-ons you are using. Can you try disabling all other addons and restarting anki?

**Comment by Sabicool** [comment]
@taihendesu Please update the addon. I believe I have fixed the issue. Please don't hesitate to the re-open this issue if the issue still persists or create a new issue should a new issue arise.
